### All User
GET http://10.1.252.149:5524/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YTJkZjA5M2QxYzI2MTUxN2UyYjNjZiIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNjg4NDE2NjYwfQ.iXBueLI1Rat7rW2cirUS8_WnSVP3ztkpWGi4PeL1YxY
